better db check

diff --git a/bin/lib/fulcrum b/bin/lib/fulcrum
--- a/bin/lib/fulcrum
+++ b/bin/lib/fulcrum
@@ -78,9 +78,16 @@ function drestart() {
 }
 
 function waitForDB() {
+  ROOT_COUNT=-1
+  ERROR_CODE=-1
+
   echo -n "Waiting until database is available"
-  while ! $(docker logs mariadb 2>&1 |grep 'ready for connections' > /dev/null 2>&1); do
-    echo -n '.'
+  # while ! $(docker logs mariadb 2>&1 |grep 'ready for connections' > /dev/null 2>&1); do
+  while [ "$ROOT_COUNT" -ne 1 ] && [ "$ERROR_CODE" -ne 0 ]; do
+    ROOT_COUNT=$(docker exec mariadb mysql -sN -e "SELECT COUNT(*) FROM mysql.user where user = 'root'")
+    ERROR_CODE=$?
+
+    echo -n ".$ROOT_COUNT.$ERROR_CODE"
     sleep .25
   done
 
