add varnishcc

diff --git a/bin/lib/general b/bin/lib/general
--- a/bin/lib/general
+++ b/bin/lib/general
@@ -374,6 +374,24 @@ function varnishrestart() {
   vout "varnish has been reloaded"
 }
 
+function varnishcc() {
+  stackStatus "exit"
+
+  # ensure we have no syntax errors
+  $SUDOCK docker exec varnish /usr/sbin/varnishd -C -f /etc/varnish/default.vcl 2>/dev/null
+  if [ $? -gt 0 ]; then
+    eout "FATAL: syntax error in varnish config it seems, quitting without restart"
+  fi
+
+  $SUDOCK docker exec varnish varnishadm "ban req.url ~ /"
+  if [ $? -gt 0 ]; then
+    echo "FATAL: unable to \"ban req.url ~ /\""
+    exit 1
+  fi
+
+  vout "varnish cache has been cleared"
+}
+
 function drupalVersion() {
   D8FILE=${FULCRUM_DOCROOT}/core/lib/Drupal.php
   D7FILE=${FULCRUM_DOCROOT}/includes/bootstrap.inc
