add varnish restart command

diff --git a/bin/lib/general b/bin/lib/general
--- a/bin/lib/general
+++ b/bin/lib/general
@@ -215,6 +215,30 @@ function haproxyrestart() {
   vout "HAProxy has been reloaded"
 }
 
+function varnishrestart() {
+  # ensure we have no syntax errors
+  docker exec varnish /usr/sbin/varnishd -C -f /etc/varnish/default.vcl 2>/dev/null
+  if [ $? -gt 0 ]; then
+    eout "FATAL: syntax error in varnish config it seems, quitting without restart"
+  fi
+
+  CFGNAME=varnish-cfg-$(date +"%Y%m%d%H%M%S")
+
+  docker exec varnish /usr/bin/varnishadm vcl.load $CFGNAME /etc/varnish/default.vcl
+  if [ $? -gt 0 ]; then
+    echo "FATAL: unable to vcl.load $CFGNAME"
+    exit 1
+  fi
+
+  docker exec varnish /usr/bin/varnishadm vcl.use $CFGNAME
+  if [ $? -gt 0 ]; then
+    echo "FATAL: unable to vcl.use $CFGNAME"
+    exit 1
+  fi
+
+  vout "varnish has been reloaded"
+}
+
 function drupalVersion() {
   D8FILE=${FULCRUM_DOCROOT}/core/lib/Drupal.php
   D7FILE=${FULCRUM_DOCROOT}/includes/bootstrap.inc
